note/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

""" Associe chaque url à une fonction de :py:mod:`note.views` qui
    est chargée de générer la page correspondante.
"""

from django.conf.urls import patterns, include, url

#: Liste des patterns d'url
urlpatterns = patterns('note.views',
    # pages de base
    url(ur'^/*$', 'login_page'),
    url(ur'^/index/*$', 'index'),
    url(ur'^/logout/*$', 'logout'),
    # consos
    url(ur'^/consos(?P<double>-double)?/*$', 'consos'),
    url(ur'^/consos(?:-double)?/(?P<de>de)?valider_transaction/(?P<idtransaction>[^/]*)$', 'toggle_transaction'),
    # dons
    url(ur'^/(?:virements|dons)/*', 'dons'),
    # les activités et invitations
    url(ur'^/(?:activite|invitation)s?(?P<admin>/admin)?/*$', 'activites'),
    url(ur'^/(?:activite|invitation)s?/(?P<idact>[^/]*)/gestion(?P<validation>/validate|/invalidate|/delete)?/*$', 'activite_gestion'),
    url(ur'^/(?:activite|invitation)s?/(?P<idact>[^/]*)/gestion/modifier/*$', 'activite_gestion_modifier'),
    url(ur'^/(?:activite|invitation)s?/(?P<idact>[^/]*)(?P<admin>/admin)?/*$', 'activite'),
    url(ur'^/(?:activite|invitation)s?/(?P<idact>[^/]*)/del_invite/(?P<idinv>[^/]*)(?P<admin>/admin)?/*$', 'del_invite'),
    # mes_activités = création d'activités
    url(ur'^/mes_activites(?:/(?P<idact>[^/]*))?(?P<delete>/delete)?/*$', 'mes_activites'),
    # la recherche et gestion des comptes
    url(ur'^/comptes_advanced/*$', 'comptes_advanced'),
    url(ur'^/search_historique_pseudo/*$', 'search_historique_pseudo'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/*$', 'comptes'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/historique/*$', 'historique_transactions'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/modifier/*$', 'modifier_compte'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/supprimer/*$', 'supprimer_compte'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/modifier/password/*$', 'password'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/modifier/photo/*$', 'update_photo'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/aliases/*$', 'aliases'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/aliases/delete(?P<delall>_all)?/(?P<idalias>[^/]*)/*$', 'unalias'),
    url(ur'^/comptes/(?P<idbde>[^/]*)/historique_pseudo/*$', 'historique_pseudo'),
    #les réadhésions
    url(ur'^/readhesions/(?P<idbde>[^/]*)/*$', 'readhesions'),
    # la gestion des boutons
    url(ur'^/boutons/*$', 'boutons'),
    url(ur'^/boutons/(?P<idbouton>[^/]*)(?P<delete>/delete)?/*$', 'boutons'),
    # les préinscription
    url(ur'^/preinscriptions?/*$', 'preinscriptions'),
    # les inscriptions
    url(ur'^/inscriptions?(?:/(?P<preid>[^/]*))?(?P<delete>/delete)?/*$', 'inscriptions'),
    # regeneration du password
    url(ur'^/regen_pw/(?P<token>[^/]*)/*$', 'regen_pw'),
    # easter egg
    url(ur'^/(?:teapot|th(?:é|e)|coffee|caf(?:é|e))/*$', 'teapot'),
)

urlpatterns += patterns('note.ajaj',
    # les pages de requêtes AJAJ
    url(ur'^/quick_search/*$', 'quick_search'),
    url(ur'^/search/*$', 'search'),
    url(ur'^/search_readhesion/*$', 'search_readhesion'),
    url(ur'^/get_boutons/*$', 'get_boutons'),
    url(ur'^/get_display_info/*$', 'get_display_info'),
    url(ur'^/get_photo/(?P<idbde>[^/]*)/*$', 'get_photo'),
    url(ur'^/do_conso/*$', 'do_conso'),
    url(ur'^/do_(?P<action>credit|retrait)/*$', 'do_credit_retrait'),
    url(ur'^/do_transfert/*$', 'do_transfert'),
)

urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

""" Module urls principal.
    
    Sert essentiellement à rediriger vers :py:mod:`note.urls`.
    
    Rajoute aussi la config pour servir les fichiers statiques quand on
    est en mode DEBUG.
"""

from django.conf.urls import patterns, include, url

import settings

if settings.DEBUG:
    # On n'utilise pas ça en prod
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#: Erreur 404 custom
handler404 = "note.views.page_not_found"

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^' + settings.NOTE_ROOT_URL.strip('/'), include('note.urls')),
    url(r'', include('note.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    # On n'utilise pas ça en prod
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % (settings.MEDIA_URL.strip('/')),
         'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

note/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from django import forms
import settings

import re
import time
import datetime

class CreditRetraitWithoutIdbde(Exception):
    """Erreur levée en cas de tentative de crédit ou retrait sans idbde."""
    pass

class LoginForm(forms.Form):
    """Formulaire de login"""
    username = forms.CharField(label="Pseudo")
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(render_value=False))
    droits = forms.ChoiceField(choices=[(k, settings.ACL_MASKS[k][0]) for k in settings._acl_masks_keys])

class InviteForm(forms.Form):
    """Formulaire d'invitation"""
    nom = forms.CharField(label="Nom")
    prenom = forms.CharField(label="Prénom")

class FrenchFloatField(forms.FloatField):
    """Un champ FloatField, mais qui accepte aussi la virgule comme séparateur"""
    def to_python(self, raw_value):
        """Conversion de la valeur texte en objet python."""
        return super(FrenchFloatField, self).to_python(raw_value.replace(",", "."))

class BaseCompteRelatedForm(forms.Form):
    """Classe de base pour tous les formulaires traitant un compte (même une préinscription)"""
    type = forms.ChoiceField(label="Type de compte", choices=[("personne", "Personne"), ("club", "Club")])
    nom = forms.CharField(label="Nom", widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    prenom = forms.CharField(label="Prénom", widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    sexe = forms.ChoiceField(label="Sexe", choices=[("M", "M"), ("F", "F")])
    mail = forms.CharField(label="E-mail", widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    tel = forms.CharField(label="Téléphone", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    adresse = forms.CharField(label="Adresse", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    pbsante = forms.CharField(label="Problème de santé", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    normalien = forms.BooleanField(label="Normalien", required=False)
    section = forms.CharField(label="Section", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))


class Regen_pwForm(forms.Form):
    """Formulaire de demande de nouveau mot de passe"""
    nom = forms.CharField(label="Nom", widget=forms.TextInput(attrs={"autocomplete" : "off"}), required=True)
    prenom = forms.CharField(label="Prénom", widget=forms.TextInput(attrs={"autocomplete" : "off"}), required=True)
    mail = forms.CharField(label="E-mail", widget=forms.TextInput(attrs={"autocomplete" : "off"}), required=True)

class CompteRelatedForm(BaseCompteRelatedForm):
    """Classe de base pour les formulaires traitant un compte avec toutes ses données
       (par opposition à une préinscription)."""
    pseudo = forms.CharField(label="Pseudo", widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    fonction = forms.CharField(label="Fonction", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    commentaire = forms.CharField(label="Commentaire", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    report_period = forms.IntegerField(label="Période des rapports (en minutes)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    bloque = forms.BooleanField(label="Bloquer le compte", required=False)
    def __init__(self, *args, **kwargs):
        super(CompteRelatedForm, self).__init__(*args, **kwargs)
        # La section n'est facultative qu'à la préinscription
        self.fields["section"].required = True
    
class CompteForm(CompteRelatedForm):
    """Formulaire pour modifier un compte"""
    def clean(self):
        """Supprime les None des champs facultatifs"""
        out = super(CompteForm, self).clean()
        if out.has_key("report_period") and (out["report_period"] == None):
            del out["report_period"]
        return out

class PreinscriptionForm(BaseCompteRelatedForm):
    """Formulaire de préinscription"""
    def clean(self):
        """Gestion des None"""
        out = super(PreinscriptionForm, self).clean()
        return out

class ReadhesionForm(forms.Form):
    """Formulaire de réadhésion"""
    wei = forms.BooleanField(label="Inscription au WEI", required=False)
    section = forms.CharField(label="Section", widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    # partie paiement
    on_note = FrenchFloatField(label="Montant supplémentaire à mettre sur la note", required=False, initial=0, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    type_de_paiement = forms.ChoiceField(label="Type de paiement", choices=[("cheque", "Chèque"), ("especes", "Espèces"), ("note", "Débiter sur note"), ("cb", "Carte bancaire"), ("virement", "Virement bancaire"), ("soge", "Société Générale")])
    pay_nom = forms.CharField(label="Nom¹ (pour le paiement)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    pay_prenom = forms.CharField(label="Prénom¹ (pour le paiement)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    pay_banque = forms.CharField(label="Banque¹ (pour le paiement)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    def clean(self):
        """des valeurs par défaut"""
        out = super(ReadhesionForm, self).clean()
        if out.has_key("on_note") and type(out["on_note"]) == float:
            out["on_note"] = int(round(100 * out["on_note"]))
        else:
            out["on_note"] = 0
        if out.has_key("section") and (out["section"] == ""):
            del out["section"]
        return out


class InscriptionForm(CompteRelatedForm):
    """Formulaire pour inscrire un nouveau compte"""
    wei = forms.BooleanField(label="Inscription au WEI", required=False)
    annee = forms.IntegerField(label="Année d'inscription (année courante si non précisée)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    # partie paiement
    on_note = FrenchFloatField(label="Montant supplémentaire à mettre sur la note", required=False, initial=0, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    type_de_paiement = forms.ChoiceField(label="Type de paiement", choices=[("cheque", "Chèque"), ("especes", "Espèces"), ("cb", "Carte bancaire"), ("virement", "Virement bancaire"), ("soge", "Société Générale")])
    pay_nom = forms.CharField(label="Nom¹ (pour le paiement)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    pay_prenom = forms.CharField(label="Prénom¹ (pour le paiement)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    pay_banque = forms.CharField(label="Banque¹ (pour le paiement)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    def clean(self):
        """des valeurs par défaut"""
        out = super(InscriptionForm, self).clean()
        if out.has_key("on_note") and type(out["on_note"]) == float:
            out["on_note"] = int(round(100 * out["on_note"]))
        else:
            out["on_note"] = 0
        if out.has_key("report_period") and (out["report_period"] == None):
            del out["report_period"]
        if out.has_key("annee") and (out["annee"] == None):
            del out["annee"]
        return out

class AliasForm(forms.Form):
    """Formulaire pour ajouter un alias"""
    alias = forms.CharField(label="Nouvel alias", widget=forms.TextInput(attrs={"autocomplete" : "off"}))

class PasswordForm(forms.Form):
    """Formulaire pour changer un mot de passe"""
    password = forms.CharField(label="Nouveau mot de passe", widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirmation du mot de passe", widget=forms.PasswordInput, required=True)
    def clean(self):
        """Vérifie que le mot de passe et sa confirmation concordent et enlève le deuxième."""
        out = super(PasswordForm, self).clean()
        if self.errors:
            return out
        if (out["password"] != out["password_confirm"]):
            raise forms.ValidationError("Le mot de passe et sa confirmation ne concordent pas.")
        else:
            del out["password_confirm"]
            return out

class SearchForm(CompteRelatedForm):
    """Formulaire pour faire une recherche avancée"""
    # On peut rechercher sur tous les champs d'un compte, plus les alias et les anciens pseudos
    alias = forms.CharField(label="Alias", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    historique = forms.CharField(label="Ancien pseudo (toujours actif)", required=False, widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    def __init__(self, *args, **kwargs):
        super(CompteRelatedForm, self).__init__(*args, **kwargs)
        # La section n'est facultative qu'à la préinscription
	for field in self.fields:
            self.fields[field].required = False

class SearchHistoriquePseudoForm(forms.Form):
    """Formulaire pour faire une recherche par ancien pseudo"""
    historique = forms.CharField(label="Ancien pseudo", widget=forms.TextInput(attrs={"autocomplete" : "off"}))
    exactfilter = forms.ChoiceField(label="Correspondance sur :",
                                    widget=forms.RadioSelect,
                                    choices=[("b", "début du mot"), ("", "n'importe où dans le mot"), ("x", "correspondance exacte")],
                                    required=False)

# Les formats de timestamps acceptés
#  Les dates
### Les %s sont là parce qu'on a besoin de placer les groupes à deux endroits
### dans la regexp, et ça nécessite qu'ils aient deux noms différents
year_match = ur'(?P<y%s>[0-9]{2}|[0-9]{4})'
ym1, ym2 = year_match % (1), year_match % (2)
month_match = ur'(?P<m%s>[0-9]{1,2})'
mm1, mm2 = month_match % (1), month_match % (2)
day_match = ur'(?P<d%s>[0-9]{1,2})'
dm1, dm2 = day_match % (1), day_match % (2)

templates/note/activite_modifier.html
{% extends "note/base.html" %}

{% block title %}Modification de l'activité n°{{activite.id}}{% endblock %}
{% block mainstyle %}main_style{% endblock %}

{% block content %}

  <div class="tabbable">
 
        <div class="labels" >
            <ul id="tab-labels">
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}activites/"  class="default {% if not isadmin %}active{% endif %}">Activités</a></h5> </li>
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}mes_activites/"  class="default">Mes activités</a></h5> </li>
		{% if hasadmin  %}
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}activites/admin/" class="default {% if isadmin %}active{% endif %}" >Administration</a></h5> </li>
		{% endif %}
        
            </ul>
        </div>

       <div id="tab-panels">
<form method="post" action="" class="form-horizontal">{% csrf_token %}
  <legend>Modification de l'activité n°{{activite.id}}</legend>
  {% include "note/form_contents.html" %}
</form>

</div>

{% endblock %}

templates/note/index.html
{% extends "note/base.html" %}

{% block title %}Index{% endblock %}
{% block mainstyle %}main_style{% endblock %}
{% block content %}
<div class="tabbable">
 <div class="labels" >
            <ul id="tab-labels">
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}index/"  class="default active">Index </a></h5> </li>


        
            </ul>
        </div>
<div id="tab-panels">
<p>
  Bienvenue sur la note Kfet 2015 !
</p>
</div>
</div>
{% endblock %}

templates/note/modifier_compte.html
{% extends "note/base.html" %}

{% block title %}Modification du compte n°{{ compte.idbde }}{% endblock %}
{% block mainstyle %}main_style{% endblock %}
{% block content %}

<div class="labels" >
            <ul id="tab-labels">
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/"  class="default "> Compte </a></h5> </li>
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/modifier/"  class="default active"> Modifier </a></h5> </li>
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/modifier/photo/" class="default">Modifier la photo </a></h5> </li>
{% if not compte.deleted %}
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/supprimer/"  class="default">Supprimer </a></h5> </li>
{% endif %}
       		       <li><h5><a href="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/historique/"  class="default"> Historique </a></h5> </li>

        
            </ul>
        </div>



<div id="tab-panels">
<div class="forms">


<div class="CompteForm">
<form action="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/modifier/" method="post">{% csrf_token %}
{{ form.non_field_errors }}
<div>
    <table class="modifier_compte">
        <caption>Compte n°{{ compte.idbde }}</caption>
        {% if "adherents_strong" in whoami.full_rights %}
            <tr><td>Nom {{form.nom.errors}}</td>    <td>{{form.nom}}</td></tr>
            <tr><td>Prénom {{form.prenom.errors}}</td>    <td>{{form.prenom}}</td></tr>
        {% else %}
            <tr><td>Nom</td>    <td>{{compte.nom}}<input type="hidden" name="nom" value="{{compte.nom}}" id="id_nom" /></td></tr>
            <tr><td>Prénom</td>    <td>{{compte.prenom}}<input type="hidden" name="prenom" value="{{compte.prenom}}" id="id_prenom" /></td></tr>
        {% endif %}
        <tr><td>Pseudo {{form.pseudo.errors}}</td>    <td>{{form.pseudo}}</td></tr>
        <tr><td>Aliases</td>    <td>{{ compte.aliases }} <a href="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/aliases/">Modifier les aliases</a></td></tr>
        <tr><td>Section {{form.section.errors}}</td>    <td>{{form.section}}</td></tr>
        <tr><td>E-mail {{form.mail.errors}}</td>    <td>{{form.mail}}</td></tr>
        <tr><td>Adresse {{form.adresse.errors}}</td>    <td>{{form.adresse}}</td></tr>
        <tr><td>Téléphone {{form.tel.errors}}</td>    <td>{{form.tel}}</td></tr>
        <tr><td>Fonction {{form.fonction.errors}}</td>    <td>{{form.fonction}}</td></tr>
        <tr><td>Type de compte {{form.type.errors}}</td>    <td>{{form.type}}</td></tr>
        <tr><td>Sexe {{form.sexe.errors}}</td>    <td>{{form.sexe}}</td></tr>
        <tr><td>Normalien {{form.normalien.errors}}</td>    <td>{{form.normalien}}</td></tr>
        {% if has_wei %}
            <tr><td>Problèmes de santé {{form.pbsante.errors}}</td>    <td>{{form.pbsante}}</td></tr>
        {% endif %}
        <tr><td>Commentaire {{form.commentaire.errors}}</td>    <td>{{form.commentaire}}</td></tr>
        <tr><td>Fréquence des rapports {{form.report_period.errors}}</td>    <td>{{form.report_period}}</td></tr>
        <tr><td>Date du dernier rapport /* TO DO */</td>    <td>{{ compte.previous_report_date }}</td></tr>
        <tr><td>Bloquer le compte {{form.bloque.errors}}</td>    <td>{{form.bloque}}</td></tr>
        <tr><td>Mot de passe</td>   <td><a href="{{ NOTE_ROOT_URL }}comptes/{{compte.idbde}}/modifier/password/">Modifier</a></tr>
    </table>
</div>
<p></p>

<div>
    <table class="droits">
        <caption>Modification des droits</caption>
        <tr class="section"><th></th>    <th>Droit</th>    <th>Surdroit</th>
        <tr class="section">
            <td style='text-align:left;'>all</td>
            <td>
                {% if "all" in whoami.full_overrights %}
                    <input type="checkbox" name="droits_all" id="id_droits_all" {% if "all" in compte.droits %}checked="checked" value="on"{% endif %}/>
                {% else %}
                    {% if "all" in compte.droits %}
                        ✔
                        <input type="hidden" name="droits_all" id="id_droits_all" value="on"/>
                    {% else %}
                        <input type="hidden" name="droits_all" id="id_droits_all" value="off"/>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if whoami.supreme %}
                    <input type="checkbox" name="surdroits_all" id="id_surdroits_all" {% if "all" in compte.surdroits %}checked="checked" value="on"{% endif %}/>
                {% else %}
                    {% if "all" in compte.surdroits %}
                        ✔
                        <input type="hidden" name="surdroits_all" id="id_surdroits_all" value="on"/>
                    {% else %}
                        <input type="hidden" name="surdroits_all" id="id_surdroits_all" value="off"/>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        {% for alias, listedroits in droits %}
        <tr class="section">
            <td style='text-align:left;'>{{ alias }}</td>
            <td>
                {% if alias in whoami.full_overrights %}
                    <input type="checkbox" name="droits_{{alias}}" id="id_droits_{{alias}}" {% if alias in compte.droits %}checked="checked" value="on"{% endif %}/>
                {% else %}
                    {% if alias in compte.droits %}
                        ✔
                        <input type="hidden" name="droits_{{alias}}" id="id_droits_{{alias}}" value="on"/>
                    {% else %}
                        <input type="hidden" name="droits_{{alias}}" id="id_droits_{{alias}}" value="off"/>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if whoami.supreme %}
                    <input type="checkbox" name="surdroits_{{alias}}" id="id_surdroits_{{alias}}" {% if alias in compte.surdroits %}checked="checked" value="on"{% endif %}/>
                {% else %}
                    {% if alias in compte.surdroits %}
                        ✔
                        <input type="hidden" name="surdroits_{{alias}}" id="id_surdroits_{{alias}}" value="on"/>
                    {% else %}
                        <input type="hidden" name="surdroits_{{alias}}" id="id_surdroits_{{alias}}" value="off"/>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
            {% for droit in listedroits %}
            <tr>
                <td style='text-align:left;text-indent: 2em;'>{{ droit }}</td>
                <td>
                    {% if droit in whoami.full_overrights %}
                        <input type="checkbox" name="droits_{{droit}}" id="id_droits_{{droit}}" {% if droit in compte.droits %}checked="checked" value="on"{% endif %}/>
                    {% else %}
                        {% if droit in compte.droits %}
                            ✔
                            <input type="hidden" name="droits_{{droit}}" id="id_droits_{{droit}}" value="on"/>
                        {% else %}
                            <input type="hidden" name="droits_{{droit}}" id="id_droits_{{droit}}" value="off"/>
                        {% endif %}
                    {% endif %}
                </td>
                <td>
                    {% if whoami.supreme %}
                        <input type="checkbox" name="surdroits_{{droit}}" id="id_surdroits_{{droit}}" {% if droit in compte.surdroits %}checked="checked" value="on"{% endif %}/>
                    {% else %}
                        {% if droit in compte.surdroits %}
                            ✔
                            <input type="hidden" name="surdroits_{{droit}}" id="id_surdroits_{{droit}}" value="on"/>
                        {% else %}
                            <input type="hidden" name="surdroits_{{droit}}" id="id_surdroits_{{droit}}" value="off"/>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        {% endfor %}
        {% for droit in droits_noalias %}
        <tr class="section">
        <tr>
            <td style='text-align:left;'>{{ droit }}</td>
            <td>
                {% if droit in whoami.full_overrights %}
                    <input type="checkbox" name="droits_{{droit}}" id="id_droits_{{droit}}" {% if droit in compte.droits %}checked="checked" value="on"{% endif %}/>
                {% else %}
                    {% if droit in compte.droits %}
                        ✔
                        <input type="hidden" name="droits_{{droit}}" id="id_droits_{{droit}}" value="on"/>
                    {% else %}
                        <input type="hidden" name="droits_{{droit}}" id="id_droits_{{droit}}" value="off"/>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if whoami.supreme %}
                    <input type="checkbox" name="surdroits_{{droit}}" id="id_surdroits_{{droit}}" {% if droit in compte.surdroits %}checked="checked" value="on"{% endif %}/>
                {% else %}
                    {% if droit in compte.surdroits %}
                        ✔
                        <input type="hidden" name="surdroits_{{droit}}" id="id_surdroits_{{droit}}" value="on"/>
                    {% else %}
                        <input type="hidden" name="surdroits_{{droit}}" id="id_surdroits_{{droit}}" value="off"/>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
<input type="submit" value="Valider" class="btn btn-primary"/>
</form>
</div>
</div>
</div>
</div>
{% endblock %}